
build: false
platform: x86
clone_folder: c:\projects\thephpleague\flysystem

cache:
  - c:\php -> appveyor.yml

init:
  - SET PATH=c:\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1

install:
  - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
  - cd c:\php
  - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.0.0-nts-Win32-VC14-x86.zip
  - IF %PHP%==1 7z x php-7.0.0-nts-Win32-VC14-x86.zip -y >nul
  - IF %PHP%==1 del /Q *.zip
  - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
  - IF %PHP%==1 copy /Y php.ini-development php.ini
  - IF %PHP%==1 echo max_execution_time=1200 >> php.ini
  - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
  - IF %PHP%==1 echo extension_dir=ext >> php.ini
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
  - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - cd c:\projects\thephpleague\flysystem
  - mkdir %APPDATA%\Composer
  - composer update --prefer-dist --no-progress --ansi

test_script:
  - cd c:\projects\thephpleague\flysystem
  - bin\phpunit.bat --verbose
