---
version: "3"
services:
  sftp:
    restart: always
    image: atmoz/sftp
    volumes:
      - ./sftp/users.conf:/etc/sftp/users.conf
      - ./sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./sftp/id_rsa.pub:/home/bar/.ssh/keys/id_rsa.pub
    ports:
      - "2222:22"
  ftp:
    restart: always
    image: delfer/alpine-ftp-server
    environment:
      USERS: 'foo|pass|/home/foo/upload'
      ADDRESS: 'localhost'
    ports:
      - "2121:21"
      - "21000-21010:21000-21010"
  ftpd:
    container_name: ftpd
    restart: always
    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: foo
      FTP_USER_PASS: pass
      FTP_USER_HOME: /home/foo
    image: stilliard/pure-ftpd
    ports:
      - "2122:21"
      - "30000-30009:30000-30009"
    command: "/run.sh -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -P localhost"
