---
name: Sub-Split Publishing
on:
  push:
    branches:
      - 2.x
  create:
    tags:
      - '*'
  delete:
    tags:
      - '*'

jobs:
  publish_subsplits:
    runs-on: ubuntu-latest
    name: Publish package sub-splits
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: 'false'
      - uses: actions/cache@v2
        id: splitsh
        with:
          path: bin/splitsh-lite
          key: ${{ runner.os }}-splitsh-lite
      - uses: frankdejonge/use-github-token@1.0.1
        with:
          authentication: 'frankdejonge:${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          user_name: 'Frank de Jonge'
          user_email: 'info@frenky.net'
      - name: Cache splitsh-lite
        id: splitsh-cache
        uses: actions/cache@v2
        with:
          path: './.splitsh'
          key: '${{ runner.os }}-splitsh'
      - uses: frankdejonge/use-subsplit-publish@1.0.0-beta.2
        with:
          source-branch: '2.x'
          config-path: './config.subsplit-publish.json'
          splitsh-path: './.splitsh/splitsh-lite'
          splitsh-version: 'v1.0.1'
