---
name: Quality Assurance
on:
  push:
    paths:
      - src/**/*.php
      - .github/workflows/quality-assurance.yml
    branches:
      - 2.x
  pull_request:
    paths:
      - src/**/*.php
      - .github/workflows/quality-assurance.yml
    branches:
      - 2.x

env:
  FLYSYSTEM_AWS_S3_KEY: '${{ secrets.FLYSYSTEM_AWS_S3_KEY }}'
  FLYSYSTEM_AWS_S3_SECRET: '${{ secrets.FLYSYSTEM_AWS_S3_SECRET }}'
  FLYSYSTEM_AWS_S3_BUCKET: '${{ secrets.FLYSYSTEM_AWS_S3_BUCKET }}'
  FLYSYSTEM_TEST_DANGEROUS_THINGS: "yes"
  FLYSYSTEM_TEST_SFTP: "yes"

jobs:
  phpunit:
    name: PHPUnit tests on ${{ matrix.php }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4' ]
        composer-flags: [ '' ]
        upgrade-aws-sdk: [ 'no' ]
        phpunit-flags: [ '--coverage-text' ]
        include:
          - php: '8.0'
            composer-flags: '--ignore-platform-req=php'
            phpunit-flags: '--no-coverage'
            upgrade-aws-sdk: 'yes'
          - php: '7.2'
            composer-flags: '--prefer-lowest'
            phpunit-flags: '--no-coverage'
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f test_files/docker-compose.yml up -d
      - name: Start an SSH Agent
        uses: frankdejonge/use-ssh-agent@1.0.0
      - run: chmod 0400 ./test_files/sftp/id_*
      - id: ssh_agent
        run: ssh-add ./test_files/sftp/id_rsa
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2
      - run: composer update --no-progress ${{ matrix.composer-flags }}
      - run: composer require --dev --ignore-platform-reqs aws/aws-sdk-php:^3.147.3
        if: ${{ matrix.upgrade-aws-sdk == 'yes' }}
      - run: php test_files/wait_for_sftp.php
      - run: php test_files/wait_for_ftp.php 2121
      - run: php test_files/wait_for_ftp.php 2122
      - run: COMPOSER_OPTS='${{ matrix.composer-flags }}' vendor/bin/phpunit ${{ matrix.phpunit-flags }}
      - run: vendor/bin/phpstan analyse -l 6 src
        if: ${{ matrix.php == '7.4' }}
      - run: vendor/bin/php-cs-fixer fix --dry-run
        if: ${{ matrix.php == '7.4' }}

